services:
  - type: web
    name: sec-edgar-mcp
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: python -m sec_edgar_mcp.server --transport sse --host 0.0.0.0 --port $PORT
    envVars:
      - key: SEC_EDGAR_USER_AGENT
        value: EdgarAnswerEngine/2.0 (evidence-first analysis; brett.vantil@crowe.com)
      - key: PORT
        generateValue: true
    healthCheckPath: /health